title: Fatal error Workflow
#    A
#    |
#    B
description: Use this to test error handling
config:
  scheduler: dynamic
entrypoint:
  ref: a

inputs:
  valid: 1
  value:
    another_valid: 2

triggers:
  - type: webhook
    ref: my_webhook
    entrypoint: a # This can be any

actions:
  - ref: a
    action: core.transform.reshape
    args:
      value:
        valid: ${{ INPUTS.valid }}

  - ref: b
    action: example.add
    depends_on:
      - a
    args:
      # This should fail
      lhs: ${{ ACTIONS.a.result.invalid }}
      rhs: ${{ INPUTS.value.another_valid }}
